import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Topbar from '@/components/shared/Topbar'
import HelloSection from '@/components/shared/HelloSection'
import InfoSection from '@/components/shared/InfoSection'
import VideoSection from '@/components/shared/VideoSection'
import Bottombar from '@/components/shared/Bottombar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="pt-16 mb-4 md:mb-8 lg:mb-12 px-4 md:px-8 xl:px-12 bg-white relative">
      {children}
      </main>

      </body>
    </html>
  )
}
